sudo: false

language: php

php:
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - php composer-setup.php --install-dir=bin
  - php composer-setup.php --filename=composer
  - composer self-update
  - composer require phpunit/phpunit

script:
  - vendor/bin/phpcs . --colors
  
