sudo: true

language: php

php:
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - composer self-update
  - composer require phpunit/phpunit
  - composer require squizlabs/php_codesniffer

script:
  - vendor/bin/phpcs . --colors
  
